package com.mb;

import java.util.*;

import javax.faces.application.FacesMessage;
import javax.faces.bean.*;
import javax.faces.context.FacesContext;

@ManagedBean(name = "regBean")
@SessionScoped()
public class RegistrationBean {
	private String username;
	private String password;
	private String confirmpassword;
	private String email;
	private String confirmemail;
	private String userRole;

	public String addUser() {
		addMessage(new FacesMessage(FacesMessage.SEVERITY_INFO,
				"User Registration Successful!!!", null));
		return "success";
	}

	public String startRegistration() {
		return "/pages/protected/user/registrationReader.xhtml?faces-redirect=true";
	}
	
	//Generated by Map
	private static Map<String,Object> userRoleMap;
	static{
		userRoleMap = new LinkedHashMap<String,Object>();
		userRoleMap.put("Reader", "USER"); //label, value
		userRoleMap.put("Librarian", "ADMIN");
	}
	 
	public Map<String,Object> getUserRoleMap() {
		return userRoleMap;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getConfirmpassword() {
		return confirmpassword;
	}

	public void setConfirmpassword(String confirmpassword) {
		this.confirmpassword = confirmpassword;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getConfirmemail() {
		return confirmemail;
	}

	public void setConfirmemail(String confirmemail) {
		this.confirmemail = confirmemail;
	}

	public String getUserRole() {
		return userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}
	
	private void addMessage(FacesMessage message) {
		FacesContext.getCurrentInstance().addMessage(null, message);
	}
}
